### PR TITLE
added a few "LEA...", removed a few "or a,a"

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mateoconlechuga** [comment]
Nice, but `lea  hl,ix+9 \ ld    sp,hl` is incorrect, it can simply be `ld   sp,ix` :)

**Comment by ghost** [comment]
You're right ! the value 9 was here because of the 3 "push" before ! (just realised that!)
Let's forget this commit, I count on you to replace with "ld sp,ix" and remove the "or a,a" ;)

**Comment by mateoconlechuga** [comment]
No; it's easy; the commit is merged in, but github handles all the differences. There's no need to forget about a commit. Closing a conversation doesn't cancel the PR.

**Comment by mateoconlechuga** [comment]
This branch had some conflicts when merging in, so I just resolved them manually in a separate commit. Thanks for the help! :)

**Pull request closed without merging**
