### PR TITLE
Some optimizations

### PR DESCRIPTION
**Pull request by ghost**
Please forget the 6 "dec sp" , I've just realised it's the same speed as the 2 push

### CODE REVIEW

**Comment by adriweb** [comment]
If you commit again on your branch (`grosged-patch-1`), it will be fixed in that pull request :)

**Comment by mateoconlechuga** [comment]
You can modify any registers you like, except ix must be saved

**Comment by ghost** [comment]
Is it possible to delete one of my commits ?

**Comment by adriweb** [comment]
You can just commit over it (and when merging, later, it can be taken care of)

**Comment by ghost** [comment]
ah okay, I begin to...understand :)

**Comment by adriweb** [comment]
>  By the way , what does mean this anti-slash.r ?

`\.r` is for handling relocations, as explained here: https://ce-programming.github.io/documentation/tutorials/asm/lib-creation/#relocations

**Pull request merged**
