### PR TITLE
Make downloading libraries easier for users

### PR DESCRIPTION
**Pull request by gavinft**
A lot of people who don't know how to use github don't know where to find releases, so this way it will be very obvious for them

### CODE REVIEW

**Comment by adriweb** [comment]
Why not. We could even link the latest 8xg file directly since github has a way to do that now.

**Comment by mateoconlechuga** [comment]
Why was this merged?

**Comment by adriweb** [comment]
Well because it does make it easier for people who arrive here for some reason and don't know github enough, to find releases?

**Comment by gavinft** [comment]
That was my thought process.

**Pull request merged**
